Repository instructlab/sdg, pull requests merged in 2024-07, with the labels that each got.

#53 updates to grounded flow
  scripts/test_freeform_skills.py
  scripts/test_grounded_skills.py
  scripts/test_knowledge.py
  src/instructlab/sdg/configs/skills/evaluate_grounded_pair.yaml
  src/instructlab/sdg/configs/skills/evaluate_grounded_questions.yaml
  src/instructlab/sdg/configs/skills/freeform_responses.yaml
  src/instructlab/sdg/configs/skills/grounded_responses.yaml
  src/instructlab/sdg/default_flows.py
Labels: CI/CD, testing

#78 Handle type conversion errors in FilterByValueBlock
  src/instructlab/sdg/filterblock.py
  tests/test_filterblock.py
Labels: testing

#81 Allow FilterByValueBlock to handle one or many values
  src/instructlab/sdg/filterblock.py
  tests/test_filterblock.py
Labels: testing

#104 Remove two files that are now unused
  src/instructlab/sdg/README.md
  src/instructlab/sdg/seed_tasks.jsonl
Labels: documentation

#86 Add a YAML based file format for pipelines
  scripts/test_freeform_skills.py
  scripts/test_grounded_skills.py
  scripts/test_knowledge.py
  src/instructlab/sdg/block.py
  src/instructlab/sdg/default_flows.py
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/importblock.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/pipelines/__init__.py
  src/instructlab/sdg/pipelines/full/__init__.py
  src/instructlab/sdg/pipelines/full/freeform_skills.yaml
  src/instructlab/sdg/pipelines/full/grounded_skills.yaml
  src/instructlab/sdg/pipelines/full/knowledge.yaml
  src/instructlab/sdg/pipelines/simple/__init__.py
  src/instructlab/sdg/pipelines/simple/freeform_skills.yaml
  src/instructlab/sdg/pipelines/simple/grounded_skills.yaml
  src/instructlab/sdg/pipelines/simple/knowledge.yaml
  src/instructlab/sdg/utilblocks.py
  tests/test_default_pipeline_configs.py
  tests/test_filterblock.py
  tests/test_importblock.py
Labels: testing

#127 pipeline: Fail explicitly on an empty dataset
  src/instructlab/sdg/pipeline.py
  tests/test_default_pipeline_configs.py
Labels: testing

#132 Automate validation of pipeline configs
  .github/workflows/lint.yml
  Makefile
  requirements-dev.txt
  scripts/validate_pipelines.py
  src/instructlab/sdg/pipelines/schema/__init__.py
  src/instructlab/sdg/pipelines/schema/v1.json
  tox.ini
Labels: CI/CD, testing

#141 Add `model_prompt` config param for LLMBlock
  docs/pipeline_config.md
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipelines/schema/v1.json
  tests/test_llmblock.py
Labels: documentation, testing

#143 filterblock: add default_value for use with convert_dtype
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/pipelines/schema/v1.json
  tests/test_filterblock.py
  tests/test_importblock.py
Labels: testing

#146 Move `gen_kwargs` down to `LLMBlock`
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/pipelines/full/grounded_skills.yaml
  src/instructlab/sdg/pipelines/full/knowledge.yaml
  src/instructlab/sdg/pipelines/schema/v1.json
  src/instructlab/sdg/pipelines/simple/freeform_skills.yaml
  src/instructlab/sdg/pipelines/simple/grounded_skills.yaml
  src/instructlab/sdg/pipelines/simple/knowledge.yaml
  tests/test_default_pipeline_configs.py
Labels: testing

#152 Remove unused requirements
  requirements.txt
  tox.ini
Labels: CI/CD, testing

#156 Fix SamplePopulatorBlock
  src/instructlab/sdg/utilblocks.py
  tests/test_sample_populator_block.py
Labels: testing

#155 Block Name In Errors
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/pipeline.py
  tests/test_pipeline.py
Labels: testing

#166 Load custom pipelines from shared data dir
  requirements.txt
  src/instructlab/sdg/generate_data.py
Labels: testing

#157 LLMBlock concurrency
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utilblocks.py
  tests/conftest.py
  tests/test_filterblock.py
  tests/test_generate_data.py
  tests/test_importblock.py
  tests/test_pipeline.py
  tests/test_sample_populator_block.py
Labels: testing

#180 Generate data for model evaluation using the MMLU benchmark
  src/instructlab/sdg/eval_data.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/pipelines/eval/mmlu_bench.yaml
  src/instructlab/sdg/pipelines/full/knowledge.yaml
  tests/test_generate_data.py
Labels: testing

#182 Add 4 new pipeline blocks
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utilblocks.py
  tests/test_utilblocks.py
Labels: testing

#215 Incorporate knowledge generation context selection improvements
  src/instructlab/sdg/datamixing.py
  tests/test_datamixing.py
Labels: testing

#203 Introduce data mixing recipe yaml files
  src/instructlab/sdg/datamixing.py
  src/instructlab/sdg/generate_data.py
  tests/test_datamixing.py
  tests/testdata/datasets/samples.jsonl
  tests/testdata/default_data_recipes/knowledge.yaml
  tests/testdata/default_data_recipes/skills.yaml
  tests/testdata/relative_path_recipe.yaml
Labels: testing

#188 tests: Add unit tests for taxonomy and model family
  src/instructlab/sdg/utils/models.py
  tests/conftest.py
  tests/taxonomy.py
  tests/test_models.py
  tests/test_sample_populator_block.py
  tests/test_taxonomy.py
Labels: testing

#222 Add data checkpointing capability
  src/instructlab/sdg/checkpointing.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  tests/test_checkpointing.py
  tests/test_generate_data.py
Labels: testing

#229 Add missing license identifiers
  src/instructlab/sdg/block.py
  src/instructlab/sdg/checkpointing.py
  src/instructlab/sdg/datamixing.py
  src/instructlab/sdg/eval_data.py
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/importblock.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/sdg.py
  src/instructlab/sdg/utilblocks.py
  tests/conftest.py
  tests/test_checkpointing.py
  tests/test_datamixing.py
  tests/test_default_pipeline_configs.py
  tests/test_filterblock.py
  tests/test_importblock.py
  tests/test_llmblock.py
  tests/test_pipeline.py
  tests/test_sample_populator_block.py
  tests/test_utilblocks.py
Labels: testing

#230 Fixing typos
  src/instructlab/sdg/datamixing.py
  src/instructlab/sdg/eval_data.py
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utils/chunking.py
  src/instructlab/sdg/utils/pandas.py
  tests/test_chunking.py
  tests/test_utilblocks.py
Labels: testing

#204 Add support for auxiliary dataset generation
  src/instructlab/sdg/configs/knowledge/spellcheck.yaml
  src/instructlab/sdg/datamixing.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/pipelines/full/knowledge.yaml
  src/instructlab/sdg/pipelines/schema/v1.json
  tests/test_default_pipeline_configs.py
Labels: testing

#64 Remove the unnecessary SDG class
  scripts/test_freeform_skills.py
  scripts/test_grounded_skills.py
  scripts/test_knowledge.py
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/sdg.py
Labels: testing
