Repository instructlab/sdg, pull requests merged in 2024-06, with the labels that each got.

#42 Add SDG library code
  pyproject.toml
  scripts/test_freeform_skills.py
  scripts/test_knowledge.py
  src/instructlab/__init__.py
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/block.py
  src/instructlab/sdg/configs/__init__.py
  src/instructlab/sdg/configs/knowledge/__init__.py
  src/instructlab/sdg/configs/knowledge/evaluate_faithfulness.yaml
  src/instructlab/sdg/configs/knowledge/evaluate_question.yaml
  src/instructlab/sdg/configs/knowledge/evaluate_relevancy.yaml
  src/instructlab/sdg/configs/knowledge/generate_questions_responses.yaml
  src/instructlab/sdg/configs/knowledge/mcq_generation.yaml
  src/instructlab/sdg/configs/skills/__init__.py
  src/instructlab/sdg/configs/skills/contexts.yaml
  src/instructlab/sdg/configs/skills/evaluate_freeform_pair.yaml
  src/instructlab/sdg/configs/skills/evaluate_freeform_questions.yaml
  src/instructlab/sdg/configs/skills/evaluate_grounded_pair.yaml
  src/instructlab/sdg/configs/skills/evaluate_grounded_questions.yaml
  src/instructlab/sdg/configs/skills/freeform_questions.yaml
  src/instructlab/sdg/configs/skills/freeform_responses.yaml
  src/instructlab/sdg/configs/skills/grounded_questions.yaml
  src/instructlab/sdg/configs/skills/grounded_responses.yaml
  src/instructlab/sdg/default_flows.py
  src/instructlab/sdg/filterblock.py
  src/instructlab/sdg/iterblock.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/logger_config.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/sdg.py
  src/instructlab/sdg/utilblocks.py
Labels: CI/CD

#50 📚 Adding Knowledge llm blocks
  scripts/test_knowledge.py
  src/instructlab/sdg/configs/knowledge/generate_questions_responses.yaml
  src/instructlab/sdg/default_flows.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utilblocks.py
Labels: ci-failure

#46 Initial CLI integration with new SDG interfaces
  .pylintrc
  pyproject.toml
  src/instructlab/sdg/configs/knowledge/simple_generate_qa.yaml
  src/instructlab/sdg/configs/skills/simple_generate_qa_freeform.yaml
  src/instructlab/sdg/configs/skills/simple_generate_qa_grounded.yaml
  src/instructlab/sdg/default_flows.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/utils.py
  src/instructlab/sdg/utils/__init__.py
  src/instructlab/sdg/utils/chunking.py
  src/instructlab/sdg/utils/json.py
  src/instructlab/sdg/utils/models.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_chunking.py
Labels: CI/CD, testing
