Repository instructlab/sdg, pull requests merged in 2024-08, with the labels that each got.

#239 Don't write empty checkpoint datasets
  src/instructlab/sdg/checkpointing.py
  tests/test_checkpointing.py
Labels: testing

#237 Document how to mix in pregenerated skills dataset
  docs/data_mixing.md
Labels: documentation, ci-failure

#242 Add taxonomy_base='null' option to support using the full taxonomy repo contents
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_taxonomy.py
Labels: testing

#226 tests: Add test to validate that generate_data() is generating the files expected
  tests/taxonomy.py
  tests/test_generate_data.py
  tests/test_taxonomy.py
  tests/testdata/test_valid_compositional_skill.yaml
  tests/testdata/test_valid_knowledge_skill.yaml
Labels: testing

#62 Use instructlab-schema package to parse qna.yaml files
  .gitignore
  .pylintrc
  .spellcheck-en-custom.txt
  docs/data_mixing.md
  pyproject.toml
  requirements.txt
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_generate_data.py
  tests/test_taxonomy.py
Labels: documentation, CI/CD, testing

#253 tests: Remove custom yaml rules
  tests/test_generate_data.py
  tests/test_taxonomy.py
Labels: testing

#256 Add more tests for golden/distractor context picking
  tests/test_datamixing.py
Labels: testing

#236 Document dataset formats
  .spellcheck-en-custom.txt
  docs/dataset_formats.md
Labels: documentation, CI/CD
