Repository instructlab/sdg, pull requests merged in 2024-09, with the labels that each got.

#269 chore: replace platformdirs with xdg-base-dirs
  docs/data_mixing.md
  requirements.txt
  src/instructlab/sdg/generate_data.py
Labels: documentation, dependencies

#262 chore: add auto-merging policy for SDG
  .github/mergify.yml
  .github/workflows/actionlint.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  .github/workflows/lint.yml
Labels: CI/CD

#278 ci: update lint workflow
  .github/mergify.yml
  .github/workflows/lint.yml
Labels: CI/CD

#286 ci: add additional autolabeling rules
  .github/mergify.yml
Labels: CI/CD

#287 github: add stale bot to sdg repo
  .github/workflows/stale_bot.yml
Labels: one-approval

#288 ci: fix lint action
  .github/workflows/lint.yml
  .pylintrc
Labels: CI/CD, one-approval
