Repository instructlab/sdg, pull requests merged in 2024-11, with the labels that each got.

#284 Integrate Context-Aware Chunking and PDF Support
  requirements.txt
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/chunking.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_chunkers.py
  tests/test_chunking.py
  tests/testdata/sample_documents/moo_deng.pdf
  tests/testdata/sample_documents/qna.yaml
Labels: dependencies, testing

#339 feat: parametrize system prompt
  src/instructlab/sdg/generate_data.py
  tests/test_generate_data.py
Labels: testing

#347 Move to Docling v2 APIs
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_chunkers.py
Labels: dependencies, testing, one-approval

#340 feat: expose max_num_tokens as configurable
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/llmblock.py
  src/instructlab/sdg/pipeline.py
  tests/test_llmblock.py
Labels: testing

#349 Upgrade docling, expand chunking testing
  .github/workflows/test.yml
  .markdownlint-cli2.yaml
  .spellcheck.yml
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  tests/functional/test_chunkers.py
  tests/functional/testdata/phoenix.md
  tests/functional/testdata/phoenix.pdf
  tests/test_chunkers.py
  tox.ini
Labels: documentation, dependencies, CI/CD, testing

#358 Don't attempt batching with InstructLab's llama-cpp-python
  src/instructlab/sdg/llmblock.py
  tests/test_llmblock.py
Labels: testing, one-approval

#356 Consolidate test sample documents into one subdir
  tests/functional/test_chunkers.py
  tests/testdata/sample_documents/phoenix.md
  tests/testdata/sample_documents/phoenix.pdf
Labels: documentation, testing, one-approval

#359 Move a spurious print to a debug log message
  src/instructlab/sdg/llmblock.py
Labels: one-approval

#361 Only use CPU for the docling OCR models
  src/instructlab/sdg/utils/chunkers.py
Labels: one-approval

#366 Data mix fix
  src/instructlab/sdg/datamixing.py
Labels: one-approval

#371 Prepare release-v0.3 branch for backports
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, ci-failure, release-branch

#372 Run the simple pipeline on small runners
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval, release-branch

#369 Prefer tesserocr over easyocr, if available
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  tests/functional/conftest.py
  tests/functional/test_imports.py
  tests/test_chunkers.py
  tests/testdata/leanimports.py
Labels: dependencies, testing, one-approval

#380 ci: add large-size E2E CI job
  .github/workflows/e2e-nvidia-l40s-x4.yml
  README.md
Labels: documentation, CI/CD, one-approval

#381 Add Release Strategy Document
  .spellcheck-en-custom.txt
  docs/release-strategy.md
Labels: documentation, CI/CD, one-approval

#362 Docling models path
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/conftest.py
  tests/test_generate_data.py
  tests/testdata/mock_xdg_data_dir/instructlab/sdg/models/config.yaml
Labels: testing

#364 Check for tokenizer in downloaded models directory
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/model_formats.py
  tests/functional/test_chunkers.py
  tests/test_chunkers.py
  tests/testdata/models/instructlab/granite-7b-lab/.gitattributes
  tests/testdata/models/instructlab/granite-7b-lab/added_tokens.json
  tests/testdata/models/instructlab/granite-7b-lab/config.json
  tests/testdata/models/instructlab/granite-7b-lab/empty.safetensors
  tests/testdata/models/instructlab/granite-7b-lab/special_tokens_map.json
  tests/testdata/models/instructlab/granite-7b-lab/tokenizer.json
  tests/testdata/models/instructlab/granite-7b-lab/tokenizer.model
  tests/testdata/models/instructlab/granite-7b-lab/tokenizer_config.json
  tests/testdata/models/invalid_gguf.gguf
  tests/testdata/models/invalid_safetensors_dir/.gitkeep
Labels: dependencies, testing

#393 Delete .gitattributes
  tests/testdata/models/instructlab/granite-7b-lab/.gitattributes
Labels: testing, one-approval

#390 fix: missing regex from actionlint action
  .github/workflows/actionlint.yml
Labels: CI/CD, one-approval

#397 Don't fail fast for unit and functional tests
  .github/workflows/test.yml
Labels: CI/CD, one-approval

#395 Adjust to slack-github-action 2.0 api changes
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval

#396 refactor: remove unused generate_data arguments
  src/instructlab/sdg/generate_data.py
Labels: one-approval

#400 Add [End] to parser cleanup tags
  src/instructlab/sdg/pipelines/full/knowledge.yaml
Labels: one-approval

#281 [Docs] Updates for SDG README
  .spellcheck-en-custom.txt
  README.md
Labels: documentation, CI/CD, one-approval

#416 Ensure knowledge docs are cloned into unique dirs
  src/instructlab/sdg/utils/taxonomy.py
  tests/test_generate_data.py
Labels: testing, one-approval
