Repository instructlab/sdg, pull requests merged in 2024-12, with the labels that each got.

#422 Move AWS_REGION from using secret to var
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#434 fix: Restrict `docling` library versions to resolve dependency issues + update `mypy` linting packages
  requirements.txt
  tox.ini
Labels: dependencies, CI/CD, testing, one-approval

#440 Update CHANGELOG.md for release v0.6.2
  .markdownlint-cli2.yaml
  CHANGELOG.md
Labels: documentation, CI/CD, one-approval

#409 Reconcile core data generation features with latest research advances
  .spellcheck-en-custom.txt
  CHANGELOG.md
  pyproject.toml
  requirements.txt
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/block.py
  src/instructlab/sdg/blocks/__init__.py
  src/instructlab/sdg/blocks/block.py
  src/instructlab/sdg/blocks/filterblock.py
  src/instructlab/sdg/blocks/iterblock.py
  src/instructlab/sdg/blocks/llmblock.py
  src/instructlab/sdg/blocks/utilblocks.py
  src/instructlab/sdg/configs/knowledge/evaluate_faithfulness.yaml
  src/instructlab/sdg/configs/knowledge/evaluate_question.yaml
  src/instructlab/sdg/configs/knowledge/evaluate_relevancy.yaml
  src/instructlab/sdg/configs/knowledge/generate_questions_responses.yaml
  src/instructlab/sdg/configs/knowledge/mcq_generation.yaml
  src/instructlab/sdg/configs/knowledge/simple_generate_qa.yaml
  src/instructlab/sdg/configs/knowledge/spellcheck.yaml
  src/instructlab/sdg/configs/skills/contexts.yaml
  src/instructlab/sdg/configs/skills/evaluate_freeform_pair.yaml
  src/instructlab/sdg/configs/skills/evaluate_freeform_questions.yaml
  src/instructlab/sdg/configs/skills/evaluate_grounded_pair.yaml
  src/instructlab/sdg/configs/skills/evaluate_grounded_questions.yaml
  src/instructlab/sdg/configs/skills/freeform_questions.yaml
  src/instructlab/sdg/configs/skills/freeform_responses.yaml
  src/instructlab/sdg/configs/skills/grounded_questions.yaml
  src/instructlab/sdg/configs/skills/grounded_responses.yaml
  src/instructlab/sdg/configs/skills/simple_generate_qa_freeform.yaml
  src/instructlab/sdg/configs/skills/simple_generate_qa_grounded.yaml
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/importblock.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/pipelines/schema/v1.json
  src/instructlab/sdg/prompts.py
  src/instructlab/sdg/registry.py
  src/instructlab/sdg/utils/models.py
  tests/functional/test_custom_block.py
  tests/test_default_pipeline_configs.py
  tests/test_filterblock.py
  tests/test_generate_data.py
  tests/test_importblock.py
  tests/test_iterblock.py
  tests/test_llmblock.py
  tests/test_models.py
  tests/test_pipeline.py
  tests/test_registry.py
  tests/test_sample_populator_block.py
  tests/test_utilblocks.py
  tests/testdata/custom_block.py
  tests/testdata/custom_block_pipeline.yaml
  tests/testdata/custom_prompt.py
Labels: documentation, dependencies, CI/CD, testing, one-approval

#398 refactor: generated_data as list
  src/instructlab/sdg/generate_data.py
Labels: one-approval

#444 Update README.md with newer content from research team
  .spellcheck-en-custom.txt
  README.md
  assets/imgs/overview.png
Labels: documentation, CI/CD, one-approval
