Repository instructlab/sdg, pull requests merged in 2024-10, with the labels that each got.

#272 Handle empty dataset from output of sdg leaf node without raising error
  src/instructlab/sdg/generate_data.py
  tests/test_generate_data.py
Labels: testing, one-approval

#303 fix: e2e job using wrong flags
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: ci-failure

#306 chore: rename 'basic-workflow-tests' to 'e2e-custom'
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#305 fix: change "group" to "tag" for mmlu_branch task config
  src/instructlab/sdg/eval_data.py
Labels: one-approval

#315 map mistral model name to mixtral
  src/instructlab/sdg/utils/models.py
Labels: ci-failure, one-approval, release-branch

#317 ci: update small E2E job to align with CLI and Training
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  README.md
Labels: documentation, CI/CD, ci-failure

#318 ci: update medium job to run as PR check
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x1.yml
  .github/workflows/e2e-nvidia-a10g-x4.yml
  README.md
Labels: documentation, CI/CD, one-approval

#319 fix: medium E2E CI job was missing HF_TOKEN
  .github/workflows/e2e-nvidia-a10g-x1.yml
Labels: CI/CD, ci-failure, one-approval

#322 ci: use org variable for AWS EC2 AMI in E2E CI jobs
  .github/workflows/e2e-nvidia-a10g-x1.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#325 ci: convert med E2E CI job to L4 GPU
  .github/mergify.yml
  .github/workflows/e2e-nvidia-l4-x1.yml
  README.md
Labels: documentation, CI/CD, one-approval
