Repository instructlab/sdg, pull requests merged in 2025-06, with the labels that each got.

#638 Use constraints files in CI
  .github/workflows/constraints-update.yml
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  constraints-dev.txt
  constraints-dev.txt.in
  requirements-files.in
  tox.ini
Labels: CI/CD, testing, one-approval

#644 ci: Disable dependabot for pip dependencies
  .github/dependabot.yml
Labels: one-approval

#654 ci: always display disk statistics
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#658 Remove torch/vllm from constraints-dev.txt.in
  constraints-dev.txt.in
Labels: one-approval

#659 chore: update constraints-dev.txt (2025-06-09)
  constraints-dev.txt
Labels: ci-failure, one-approval

#668 Add AWS region fallback to functional-gpu workflow
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
Labels: CI/CD

#666 chore: Remove remnants of small e2e job
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  README.md
  docs/ci.md
Labels: documentation, CI/CD, one-approval

#636 Schedule a Mon-Thurs daily e2e-medium job run
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, one-approval

#674 chore: update constraints-dev.txt (2025-06-16)
  constraints-dev.txt
Labels: one-approval
