Repository instructlab/sdg, pull requests merged in 2025-04, with the labels that each got.

#595 Add llama chat template to the prompt registry
  src/instructlab/sdg/prompts.py
Labels: ci-failure

#557 Update PDF extraction and OCR options for hybrid chunking
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/functional/test_chunkers.py
  tests/test_chunkers.py
  tests/test_taxonomy.py
  tox.ini
Labels: dependencies, CI/CD, testing

#598 Add pipelines and configs for llama as a teacher model
  src/instructlab/sdg/configs/knowledge/atomic_facts.yaml
  src/instructlab/sdg/configs/knowledge/detailed_summary.yaml
  src/instructlab/sdg/configs/knowledge/extractive_summary.yaml
  src/instructlab/sdg/pipelines/llama/__init__.py
  src/instructlab/sdg/pipelines/llama/freeform_skills.yaml
  src/instructlab/sdg/pipelines/llama/grounded_skills.yaml
  src/instructlab/sdg/pipelines/llama/knowledge.yaml
Labels: ci-failure, one-approval

#600 Verify that we can load mixed unmasked datasets
  tests/test_datamixing.py
Labels: testing, one-approval

#542 Subset Selection Integration
  requirements.txt
  src/instructlab/sdg/encoders/__init__.py
  src/instructlab/sdg/encoders/arctic_encoder.py
  src/instructlab/sdg/subset_select.py
  src/instructlab/sdg/subset_selection.py
  src/instructlab/sdg/utils/subset_selection_utils.py
  tests/functional/test_subset_selection.py
  tests/test_subset_selection.py
Labels: dependencies, testing, one-approval

#603 Unpin submodlib-py and remove linux only install constraint
  requirements.txt
Labels: dependencies, ci-failure, one-approval

#605 Disable the e2e-small CI tests
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#606 Update CHANGELOG.md for v0.8.0 and v0.8.1
  .spellcheck-en-custom.txt
  CHANGELOG.md
Labels: documentation, CI/CD

#608 Fix subset selection dynamic imports
  src/instructlab/sdg/encoders/__init__.py
  src/instructlab/sdg/subset_selection.py
  tests/test_subset_selection.py
Labels: testing

#616 Fix up mypy in recent CI testing
  src/instructlab/sdg/utils/chunkers.py
  tox.ini
Labels: CI/CD, testing, ci-failure, one-approval
