Repository instructlab/sdg, pull requests merged in 2025-01, with the labels that each got.

#465 chore!: Update PyTorch to 2.5
  requirements.txt
Labels: dependencies

#468 fix: typo in mergify configuration
  .github/mergify.yml
Labels: CI/CD, one-approval

#473 Update CHANGELOG.md for v0.6.3
  CHANGELOG.md
Labels: documentation, one-approval

#470 Add a CONTRIBUTING.md with basic dev setup instructions
  CONTRIBUTING.md
Labels: documentation, one-approval

#475 chore: Change default temporary write directory in all e2e CI jobs from `tmpfs` to `/home/tmp`
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#479 fix: Remove unused PyTorch dependency
  CHANGELOG.md
  requirements.txt
Labels: documentation, dependencies, one-approval

#430 Refactor Document Chunker to always use docling
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/functional/test_chunkers.py
  tests/test_chunkers.py
  tests/test_generate_data.py
  tests/test_taxonomy.py
  tests/testdata/test_valid_knowledge_skill.yaml
Labels: testing, one-approval

#435 Document updating of CHANGELOG.md as part of release
  .spellcheck-en-custom.txt
  docs/release-strategy.md
Labels: documentation, CI/CD, one-approval

#443 Split up `generate_data` and add a `mix_datasets` top level API
  .gitignore
  docs/examples/mix_datasets/concatenate_recipe.yaml
  docs/examples/mix_datasets/dataset_1.jsonl
  docs/examples/mix_datasets/dataset_2.jsonl
  docs/examples/mix_datasets/example_mixing.py
  docs/examples/mix_datasets/weighted_recipe.yaml
  src/instructlab/sdg/__init__.py
  src/instructlab/sdg/datamixing.py
  src/instructlab/sdg/generate_data.py
  src/instructlab/sdg/pipeline.py
  src/instructlab/sdg/utils/json.py
  src/instructlab/sdg/utils/models.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/conftest.py
  tests/functional/__init__.py
  tests/functional/conftest.py
  tests/functional/test_examples.py
  tests/functional/test_granular_api.py
  tests/mockllmblock.py
  tests/taxonomy.py
  tests/test_generate_data.py
  tests/test_models.py
  tests/testdata/mock_pipelines/freeform_skills.yaml
  tests/testdata/mock_pipelines/grounded_skills.yaml
  tests/testdata/mock_pipelines/knowledge.yaml
Labels: documentation, testing, one-approval

#461 Implement LLMMessagesBlock
  src/instructlab/sdg/blocks/llmblock.py
  tests/test_llmblock.py
Labels: testing, one-approval

#484 Adding Batching After Every Block
  src/instructlab/sdg/pipeline.py
  tests/test_pipeline.py
Labels: testing, one-approval

#493 use render method for jinja template, add unit tests
  src/instructlab/sdg/blocks/llmblock.py
  tests/test_llmblock.py
Labels: testing, one-approval

#495 Update release notes for v0.7.0
  .spellcheck-en-custom.txt
  CHANGELOG.md
Labels: documentation, CI/CD, one-approval

#375 Add tests for the datamixing ensuring all reqd datasets are mixed appropriately
  tests/test_datamixing.py
  tests/testdata/datasets/auxiliary.jsonl
  tests/testdata/datasets/knowledge.jsonl
  tests/testdata/datasets/knowledge_skills.jsonl
Labels: testing, one-approval

#448 Update URLs in `docs/dataset_formats.md` to point to the new InstructLab `scripts/test-data` files
  .spellcheck-en-custom.txt
  docs/dataset_formats.md
Labels: documentation, CI/CD, one-approval

#519 Add issue templates for bug, feat and team additions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/team_recommend.md
  .markdownlint-cli2.yaml
Labels: documentation, CI/CD

#408 Add FAQ.md to provide sample estimation guidelines
  docs/FAQ.md
Labels: documentation, one-approval

#524 Add Python 3.12 to our unit and functional tests
  .github/workflows/test.yml
  tox.ini
Labels: CI/CD, testing, one-approval

#526 Add missing pipeline schema for IterBlock
  src/instructlab/sdg/pipelines/schema/v1.json
Labels: one-approval
