Repository instructlab/sdg, pull requests merged in 2025-03, with the labels that each got.

#570 Update CHANGELOG.md for v0.7.2
  CHANGELOG.md
Labels: documentation, release-branch

#571 Update CHANGELOG.md for v0.7.2
  CHANGELOG.md
Labels: documentation, one-approval

#582 Fix typo in mergify config for functional-gpu-small
  .github/mergify.yml
Labels: CI/CD

#581 Remove the max version from our datasets dependency
  requirements.txt
Labels: dependencies

#574 Update Docling version and improve OCR options handling with new docling ver.
  pyproject.toml
  requirements.txt
  src/instructlab/sdg/utils/chunkers.py
  src/instructlab/sdg/utils/taxonomy.py
  tests/functional/test_chunkers.py
  tests/test_chunkers.py
  tox.ini
Labels: dependencies, CI/CD, testing

#584 Add v0.7.3 entry to changelog
  CHANGELOG.md
Labels: documentation, one-approval
