Repository instructlab/sdg, pull requests merged in 2025-05, with the labels that each got.

#619 feat: add markdown documentation for subset selection
  .spellcheck-en-custom.txt
  docs/subset_selection.md
Labels: documentation, CI/CD

#623 docs: add CI documentation
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
  .markdownlint-cli2.yaml
  .spellcheck-en-custom.txt
  docs/ci.md
  tests/unit/__init__.py
  tests/unit/test_checkpointing.py
  tests/unit/test_chunkers.py
  tests/unit/test_datamixing.py
  tests/unit/test_default_pipeline_configs.py
  tests/unit/test_filterblock.py
  tests/unit/test_generate_data.py
  tests/unit/test_iterblock.py
  tests/unit/test_llmblock.py
  tests/unit/test_models.py
  tests/unit/test_pipeline.py
  tests/unit/test_registry.py
  tests/unit/test_sample_populator_block.py
  tests/unit/test_taxonomy.py
  tests/unit/test_utilblocks.py
  tox.ini
Labels: documentation, CI/CD, testing

#631 Add the fallback logic to our e2e-large job
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval

#642 ci: report inode utilization
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
Labels: CI/CD
