Repository instructlab/sdg, pull requests merged in 2025-02, with the labels that each got.

#534 Disable medium test by default with older release branches
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, ci-failure, one-approval, release-branch

#531 Disable medium test by default with older release branches
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, one-approval, release-branch

#530 ci: Don't require secrets in medium e2e test
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, one-approval

#536 requirements: Move comment closer to tenacity where it belongs
  requirements.txt
Labels: dependencies, one-approval

#466 Add simple and full knowledge pipeline functional tests
  .github/mergify.yml
  .github/workflows/functional-gpu-nvidia-t4-x1.yml
  pyproject.toml
  requirements-dev.txt
  scripts/test_knowledge.py
  tests/functional/conftest.py
  tests/functional/llama_cpp_helpers.py
  tests/functional/test_full_pipeline.py
  tests/functional/test_simple_pipeline.py
  tox.ini
Labels: dependencies, CI/CD, testing, one-approval

#555 Only use docling[tesserocr] on non-Macs
  requirements.txt
Labels: dependencies

#549 Add empty list check for element before table to fix "list index out of range"
  src/instructlab/sdg/utils/chunkers.py
Labels: ci-failure

#550 Adding Example Annotation with Showcase Notebook
  docs/examples/annotation/annotation_example.ipynb
  docs/examples/annotation/annotation_pipeline.yaml
  docs/examples/annotation/annotation_results.jsonl
  docs/examples/annotation/detailed_annotation_config.yaml
  docs/examples/annotation/simple_annotation_config.yaml
Labels: documentation, one-approval
